{"tag": "function", "depth": 1, "time": 1665307378.0499275, "data": {"name": "start_app", "call_args": {"package": "com.gonline.AppBravoCasino", "activity": null}, "start_time": 1665307376.0875118, "ret": null, "end_time": 1665307378.0499275}}
{"tag": "function", "depth": 3, "time": 1665307382.0235746, "data": {"name": "_cv_match", "call_args": {"": {"filename": "tpl1658887244324.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": null, "resolution": [], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "screen": "array([[[128,   0,  43],\n        [141,  10,  61],\n        [176,  53, 103],\n        ...,\n        [171,  40,  97],\n        [201,  55, 119],\n        [139,   0,  52]],\n\n       [[127,   0,  42],\n        [157,  23,  75],\n        [169,  46,  96],\n        ...,\n        [159,  28,  85],\n        [191,  48, 110],\n        [147,   0,  62]],\n\n       [[132,   0,  47],\n        [176,  42,  94],\n        [157,  34,  84],\n        ...,\n        [145,  16,  73],\n        [184,  44, 105],\n        [170,  23,  85]],\n\n       ...,\n\n       [[ 84,  15,  72],\n        [ 85,  16,  73],\n        [ 88,  17,  74],\n        ...,\n        [ 85,  17,  74],\n        [ 84,  16,  73],\n        [ 81,  16,  72]],\n\n       [[ 84,  15,  72],\n        [ 85,  16,  73],\n        [ 88,  17,  74],\n        ...,\n        [ 85,  17,  74],\n        [ 84,  16,  73],\n        [ 81,  16,  72]],\n\n       [[ 84,  15,  72],\n        [ 85,  16,  73],\n        [ 88,  17,  74],\n        ...,\n        [ 85,  17,  74],\n        [ 84,  16,  73],\n        [ 81,  16,  72]]], dtype=uint8)"}, "start_time": 1665307382.0196693, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = _imread()\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(filepath)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1658887244324.png\n", "end_time": 1665307382.0235746}}
{"tag": "function", "depth": 2, "time": 1665307382.0255287, "data": {"name": "loop_find", "call_args": {"query": {"filename": "tpl1658887244324.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": null, "resolution": [], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "timeout": 100, "interval": 3, "intervalfunc": null, "threshold": null}, "start_time": 1665307378.0499275, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = _cv_match(screen)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = _imread()\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(filepath)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1658887244324.png\n", "end_time": 1665307382.0255287}}
{"tag": "function", "depth": 1, "time": 1665307382.0284572, "data": {"name": "wait", "call_args": {"v": {"filename": "tpl1658887244324.png", "_filepath": null, "threshold": 0.7, "target_pos": 5, "record_pos": null, "resolution": [], "rgb": false, "scale_max": 800, "scale_step": 0.005, "__class__": "Template"}, "timeout": 100, "interval": 3, "intervalfunc": null}, "start_time": 1665307378.0499275, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\api.py\", line 592, in wait\n    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=intervalfunc)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = _cv_match(screen)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = _imread()\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(filepath)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1658887244324.png\n", "end_time": 1665307382.02748}}
{"tag": "function", "depth": 2, "time": 1665307382.5293107, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1665307382.0313852, "ret": {"screen": "1665307382200.jpg", "resolution": [720, 1280]}, "end_time": 1665307382.5293107}}
{"tag": "info", "depth": 1, "time": 1665307382.5400517, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\bruce.chen\\Desktop\\\u81ea\u52d5\u5316\\V5.0\\MobileTestRun.air\\MobileTestRun.py\", line 41, in <module>\n    Itemcard_Interrupt.Haotian_Use_Itemcard_Interrupt()  # \u6d69\u5929\u4e32\u63a5\u904a\u6232 \u865b\u5bf6\u5361 \u65b7\u88dc\u6d41\u7a0b\n  File \"C:\\Users\\bruce.chen\\Desktop\\\u81ea\u52d5\u5316\\V5.0\\.\\MobileTestRun.air\\TestCase\\Itemcard_Interrupt.air\\Itemcard_Interrupt.py\", line 26, in Haotian_Use_Itemcard_Interrupt\n    LC001.Haotian_SPIN_Start() # \u78ba\u8a8d\u6709\u9032\u5165\u904a\u6232\u5167\n  File \"C:\\Users\\bruce.chen\\Desktop\\\u81ea\u52d5\u5316\\V5.0\\.\\MobileTestRun.air\\TestAction\\LC001.air\\LC001.py\", line 62, in Haotian_SPIN_Start\n    wait(Template(r\"tpl1658887244324.png\"), timeout=100, interval=3)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\api.py\", line 592, in wait\n    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=intervalfunc)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 69, in loop_find\n    match_pos = query.match_in(screen)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 154, in match_in\n    match_result = _cv_match(screen)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 169, in _cv_match\n    ori_image = _imread()\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\core\\cv.py\", line 202, in _imread\n    return aircv.imread(filepath)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: tpl1658887244324.png\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\cli\\runner.py\", line 70, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), scope)\n  File \"C:\\Users\\bruce.chen\\Desktop\\\u81ea\u52d5\u5316\\V5.0\\MobileTestRun.air\\MobileTestRun.py\", line 49, in <module>\n    simple_report(__file__ ,logpath=r\".\\MobileTestRun.air\\TestReport\\\\\" + timenow + \"\\log\" ,output=r\".\\MobileTestRun.air\\TestReport\\\\\" + timenow + \"\\log.html\")\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 520, in simple_report\n    rpt.report(HTML_TPL, output_file=output)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 511, in report\n    data = report_data(output_file=output_file, record_list=record_list)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 453, in report_data\n    steps = _analyse()\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 119, in _analyse\n    translated_steps = [_translate_step(s) for s in steps]\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 119, in <listcomp>\n    translated_steps = [_translate_step(s) for s in steps]\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 126, in _translate_step\n    code = _translate_code(step)\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\report\\report.py\", line 269, in _translate_code\n    crop_img = imread(os.path.join(script_root, value['filename']))\n  File \"C:\\Users\\bruce.chen\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\airtest\\aircv\\aircv.py\", line 15, in imread\n    raise FileNotExistError(\"File not exist: %s\" % filename)\nairtest.aircv.error.FileNotExistError: File not exist: C:\\Users\\bruce.chen\\Desktop\\\u81ea\u52d5\u5316\\V5.0\\MobileTestRun.air\\tpl1658887244324.png\n"}}
